version: "2"
services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf/local:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./userdata:/home/node/app/userdata
    links:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - app-network

volumes:
  data:
networks:
  app-network:
    driver: bridge
